# Generated by Django 3.1.1 on 2020-09-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='e9943be53e', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
