# Generated by Django 3.1.1 on 2020-09-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200925_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default='2871662bc4', editable=False, primary_key=True, serialize=False),
        ),
    ]
