# Generated by Django 3.1.1 on 2020-09-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200925_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default='42251a38a5', editable=False, primary_key=True, serialize=False),
        ),
    ]
