# Generated by Django 3.1.1 on 2020-09-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200925_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default='853aeb7ad8', editable=False, primary_key=True, serialize=False),
        ),
    ]
