# Generated by Django 3.1.1 on 2020-09-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200925_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='4b438c9471', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
