# Generated by Django 3.1.1 on 2020-09-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200925_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='timezone',
            new_name='tz',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='38cac37933', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
